version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    ports:
      - 4000:80
    volumes:
      - D:/download:/srv
    environment:
      - FB_BASEURL=/
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 128M