version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    restart: always
  rnacos:
    image: qingpan/rnacos:stable
    ports:
      - 10848:10848
      - 9848:9848
      - 9849:9849
    restart: always